# Generated by Django 3.2.18 on 2023-05-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_imgs/'),
        ),
    ]
