# Generated by Django 3.2.18 on 2023-05-24 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('movies', models.ManyToManyField(related_name='otts', to='movies.Movie')),
                ('users', models.ManyToManyField(related_name='otts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
