# Generated by Django 3.2.18 on 2023-05-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_otts_ott'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='logo_path',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
